CREATE TABLE adverts(
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	title VARCHAR NOT NULL,
	content VARCHAR NOT NULL
);
